server:
  port: 8081

spring:
  application:
    name: tc-f5-ms-login
  cloud:
    discovery:
      enabled: true
    function:
      definition: validateTokenRevocation
  mail:
    host: smtp.gmail.com
    port: 587
    username: techchalengef5@gmail.com
    password: rkzf fgbb kyiq oghr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    default-encoding: UTF-8

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8021/realms/tech-fiap-qa/protocol/openid-connect/certs

  datasource:
    url: jdbc:mysql://localhost:3306/tc_f5_ms_login?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: rabbit
    virtual-host: /
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5s
          multiplier: 2

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        security: debug

keycloak:
  realm: tech-fiap-qa
  resource: mslogin
  disable-trust-manager: false
  use-resource-role-mappings: true
  ssl-required: none
  principal-attribute: preferred_username
  auth-server-url: http://localhost:8021
  public-client: false
  credentials:
    secret: ml5ioShdkK458ux5aJANFGYWHzlLNknM

url-email: http://localhost:8081
