spring:
  application:
    name: tc-f5-ms-login
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/authenticate-fiap/protocol/openid-connect/certs
  cloud:
    discovery:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/tc_f5_ms_login?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    username: admin
    password: rabbit
    port: 5672
    virtual-host: /
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5s
          multiplier: 2

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    instanceId: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

keycloak:
  auth-server-url: http://localhost:8080
  realm: authenticate-fiap
  resource: tc-f5-fiap
  bearer-only: true
  credentials:
    secret: 9wrC1ubAiV2OdTpXcrCjUIgls1iK9b4X
  use-resource-role-mappings: true
  ssl-required: external
  principal-attribute: preferred_username