services:
  keycloak-fiap-db:
    image: postgres:15
    container_name: keycloak-fiap-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"

  keycloak-fiap:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak-fiap
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-fiap-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
    ports:
      - "8021:8080"
    depends_on:
      - keycloak-fiap-db
